### ISSUE TITLE
Error while trying to export CityJson to b3dm

### ISSUE THREAD

**Issue by webadrian** [cityjson/cjio#119]
Hello,

When I'm trying to export a cityjson to b3dm I'm getting the following error:

 cjio 3dbag_v210908_fd2cee53_5892.json export --format b3dm .
Parsing 3dbag_v210908_fd2cee53_5892.json
Traceback (most recent call last):
  File "/usr/local/bin/cjio", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1101, in _process_result
    value = ctx.invoke(self.result_callback, value,
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cjio/cjio.py", line 103, in process_pipeline
    cm = processor(cm)
  File "/usr/local/lib/python3.8/dist-packages/cjio/cjio.py", line 192, in processor
    exporter(cm)
  File "/usr/local/lib/python3.8/dist-packages/cjio/cjio.py", line 171, in exporter
    b3dm = cm.export2b3dm()
  File "/usr/local/lib/python3.8/dist-packages/cjio/cityjson.py", line 1585, in export2b3dm
    glb = convert.to_glb(self.j)
  File "/usr/local/lib/python3.8/dist-packages/cjio/convert.py", line 188, in to_glb
    tri = geom_help.triangulate_face(face, vertexlist)
  File "/usr/local/lib/python3.8/dist-packages/cjio/geom_help.py", line 88, in triangulate_face
    xy = to_2d(p, n)
  File "/usr/local/lib/python3.8/dist-packages/cjio/geom_help.py", line 39, in to_2d
    if((n==x3).all()):
AttributeError: 'bool' object has no attribute 'all'

How can I fix this? (city json attached)
[3dbag_v210908_fd2cee53_5892.zip](https://github.com/cityjson/cjio/files/7563858/3dbag_v210908_fd2cee53_5892.zip)

Thank you in advance!
.

**Comment by hugoledoux** [comment]
Thanks for reporting this.

The triangulation crashes with that specific surface, I'll look into this soon.

Note to self: with cjio 0.7.0 and operator "triangulate" it does work, so would it be the double function? To remove.

**Comment by balazsdukai** [comment]
Fixed by 98a21a1479d0f3d1285583f0f9be5ac345f6c310
