### ISSUE TITLE
Error outputting to STL format

### ISSUE THREAD

**Issue by ipadjen** [cityjson/cjio#126]
Tried outputting 3D BAG tile number 5910, and I get the following error while outputting to STL format:

Traceback (most recent call last):
  File "/home/ivan/.local/bin/cjio", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1101, in _process_result
    value = ctx.invoke(self.result_callback, value,
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ivan/.local/lib/python3.8/site-packages/cjio/cjio.py", line 105, in process_pipeline
    cm = processor(cm)
  File "/home/ivan/.local/lib/python3.8/site-packages/cjio/cjio.py", line 210, in processor
    exporter(cm)
  File "/home/ivan/.local/lib/python3.8/site-packages/cjio/cjio.py", line 162, in exporter
    re = cm.export2stl()
  File "/home/ivan/.local/lib/python3.8/site-packages/cjio/cityjson.py", line 1645, in export2stl
    out.write("facet normal %f %f %f\nouter loop\n" % (n[0], n[1], n[2]))
NameError: name 'n' is not defined

It happens whether I use the 'triangulate' command or not.

**Comment by balazsdukai** [comment]
Which `cjio --version` are you using?

**Comment by ipadjen** [comment]
0.7.2
