### ISSUE TITLE
Unable to convert to obj file.

### ISSUE THREAD

**Issue by nokonoko1203** [cityjson/cjio#147]
**Describe the bug**
Unable to convert to obj file.

**cjio version**
```bash
$ cjio --version
cjio v0.7.6; supports CityJSON v1.1
```

**To Reproduce**
```bash
$ cjio data/assets/52385628_bldg_6697_op_upgraded.json export obj data/assets/52385628_bldg_6697_op.obj
Parsing data/assets/52385628_bldg_6697_op_upgraded.json
Exporting CityJSON to OBJ (.../data/assets/52385628_bldg_6697_op_upgraded.obj)
Internal error in segmentintersection():
  Topological inconsistency after splitting a segment.
  Please report this bug to jrs@cs.berkeley.edu
  Include the message above, your input data set, and the exact
    command line you used to run Triangle.
```

**Expected behavior**
The specified CityJSON must be able to be converted to an OBJ format file.

**Screenshots**
No screenshots available.

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version 12.4

**Additional context**

Hello. Thank you for your wonderful library.

A project called PLATEAU, promoted by the Japanese Ministry of Land, Infrastructure, Transport and Tourism, has created CityGML for various Japanese cities.
The data for Tokyo is publicly available and we download and use it.
https://www.geospatial.jp/ckan/dataset/plateau-tokyo23ku

The goal is to extract individual cityobjects from this data, triangulate the faces, and then convert them to trimesh objects, but this could not be done using only the functionality that exists in cjio.

I tried to convert the Tokyo data to cityJSON using citygml-tools and then to obj files using cjio, but the following error occurred.
I think this error is due to the fact that triangulation is not possible.

```bash
$ cjio data/assets/52385628_bldg_6697_op_upgraded.json export obj data/assets/52385628_bldg_6697_op.obj
Parsing data/assets/52385628_bldg_6697_op_upgraded.json
Exporting CityJSON to OBJ (.../data/assets/52385628_bldg_6697_op_upgraded.obj)
Internal error in segmentintersection():
  Topological inconsistency after splitting a segment.
  Please report this bug to jrs@cs.berkeley.edu
  Include the message above, your input data set, and the exact
    command line you used to run Triangle.
```

The version of cjio is 0.7.6.

```python
>> cjio.__version__
'0.7.6'
```

The data is attached, and was generated using the following procedure.
Extract `52385628_bldg_6697_op.gml` from the downloaded zip file and assume it is stored in the directory `data/assets`.
The following jupyter notebook was used to modify the schema of CityGML, projection conversion, and conversion to CityJSON.
In addition, we have also upgraded CityJSON.

[52385628_bldg_6697_op_upgraded.json.zip](https://github.com/cityjson/cjio/files/9874407/52385628_bldg_6697_op_upgraded.json.zip)

```ipynb
TARGET_CRS=6676
YOUR_GML_NAME="52385628_bldg_6697_op"
REPLACED=f"{YOUR_GML_NAME}_replace_schema"

base_dir = "./"
assets = base_dir + "data/assets/"
outputs = base_dir + "data/outputs/"

in_path = f"{assets}{YOUR_GML_NAME}.gml"
out_path = f"{assets}{REPLACED}.gml"

!sed -e "s|http://www.kantei.go.jp/jp/singi/tiiki/toshisaisei/itoshisaisei/iur/uro/1.4|https://www.chisou.go.jp/tiiki/toshisaisei/itoshisaisei/iur/uro/1.5|g" \
-e "s|http://www.kantei.go.jp/jp/singi/tiiki/toshisaisei/itoshisaisei/iur/schemas/uro/1.4/urbanObject.xsd|https://www.chisou.go.jp/tiiki/toshisaisei/itoshisaisei/iur/schemas/uro/1.5/urbanObject.xsd|g" $in_path > $out_path

!docker run --rm -u 1000 -v `pwd`:/data citygml4j/citygml-tools reproject --target-crs=6676 $out_path
!docker run --rm -u 1000 -v `pwd`:/data citygml4j/citygml-tools to-cityjson data/assets/52385628_bldg_6697_op_replace_schema__reprojected.gml
!cjio data/assets/52385628_bldg_6697_op_replace_schema__reprojected.json upgrade save data/assets/52385628_bldg_6697_op_upgraded.json
```

An error occurs when triangulate is run on the generated CityJSON.

```bash
$ cjio data/assets/52385628_bldg_6697_op_upgraded.json triangulate --sloppy save data/assets/52385628_bldg_6697_op_triangulated.json
Parsing data/assets/52385628_bldg_6697_op_upgraded.json
Triangulate the CityJSON file
Traceback (most recent call last):
  File ".../opt/anaconda3/envs/jupyter/bin/cjio", line 8, in <module>
    sys.exit(cli())
  File ".../opt/anaconda3/envs/jupyter/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File ".../opt/anaconda3/envs/jupyter/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File ".../opt/anaconda3/envs/jupyter/lib/python3.9/site-packages/click/core.py", line 1689, in invoke
    return _process_result(rv)
  File ".../opt/anaconda3/envs/jupyter/lib/python3.9/site-packages/click/core.py", line 1626, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File ".../opt/anaconda3/envs/jupyter/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File ".../opt/anaconda3/envs/jupyter/lib/python3.9/site-packages/cjio/cjio.py", line 92, in process_pipeline
    cm = processor(cm)
  File ".../opt/anaconda3/envs/jupyter/lib/python3.9/site-packages/cjio/cjio.py", line 723, in processor
    cm.triangulate(sloppy)
  File ".../opt/anaconda3/envs/jupyter/lib/python3.9/site-packages/cjio/cityjson.py", line 2013, in triangulate
    if texture[key]['values'][sidx][i][ii][0] is None:
IndexError: list index out of range
```

Since triangulation is not possible, conversion to obj format is also not possible.

```bash
$ cjio data/assets/52385628_bldg_6697_op_upgraded.json export obj data/assets/52385628_bldg_6697_op.obj
Parsing data/assets/52385628_bldg_6697_op_upgraded.json
Exporting CityJSON to OBJ (.../data/assets/52385628_bldg_6697_op_upgraded.obj)
Internal error in segmentintersection():
  Topological inconsistency after splitting a segment.
  Please report this bug to jrs@cs.berkeley.edu
  Include the message above, your input data set, and the exact
    command line you used to run Triangle.
```

Currently, I have no choice but to refer to the cjio implementation and create the following function to convert the cityobject to a trimesh object, but is there a better way?
With this implementation, the faces that could not be triangulated are skipped.

```python
def cityobject_to_mesh(city_object, lod=1):
    if lod > 2:
        raise ValueError("LOD3 and above are not supported.")

    try:
        geometry = list(filter(lambda x: int(x.lod) == int(lod), city_object.geometry))[
            0
        ]
    except IndexError:
        print(
            f"tries lod={lod - 1} since {city_object.id} does not have an object of the specified LOD (lod={lod})"
        )
        lod -= 1

        if lod == 0:
            print("LOD0 is not a 3d object and is not supported")
            return

        geometry = list(filter(lambda x: int(x.lod) == int(lod), city_object.geometry))[
            0
        ]

    face_by_indices = geometry.build_index()
    boundaries = face_by_indices[0]
    vertices = np.array(list(face_by_indices[1].keys()))

    try:
        # Create an empty array and add triangulated faces to it
        trifaces = np.empty((0, 3), dtype=np.int64)
        for shell in boundaries:
            for face in shell:
                # If the surface has already been triangulated, use it as is.
                if (len(face) == 1) and (len(face[0]) == 3):
                    tris = np.array(face)
                    continue

                surface_indexes = np.array([], dtype=np.int32)
                for ring in face:
                    surface_indexes = np.hstack((surface_indexes, np.array(ring)))

                surface = vertices[surface_indexes]
                normal = geom_help.get_normal_newell(surface)

                surface_2d = np.zeros((surface.shape[0], 2))
                for i, vertex in enumerate(surface):
                    xy = geom_help.to_2d(vertex, normal[0])
                    surface_2d[i][0] = xy[0]
                    surface_2d[i][1] = xy[1]

                number_of_rings = np.array([surface_2d.shape[0]])
                triangle_2d_mesh = earcut.triangulate_float64(surface_2d, number_of_rings)

                for i, each in enumerate(triangle_2d_mesh):
                    triangle_2d_mesh[i] = int(surface_indexes[each])

                tris = np.array(triangle_2d_mesh.reshape(-1, 3).tolist())         

                if tris.size == 0:
                    print(f"Some aspects of {city_object.id} were skipped because they cannot be triangulated")
                    continue

                trifaces = np.vstack((trifaces, tris))

        mesh = trimesh.Trimesh(vertices=vertices, faces=trifaces)
    except Exception as e:
        raise Exception(e, city_object.id)

    return mesh
```

**Comment by hugoledoux** [comment]
sorry for very late reply, missed that one somehow...

The error is cause by invalid geometries (duplicated segments, points, intersections) and the triangulator we use (Shewchuk's Triangle) crashes... There is nothing we can do about this in cjio, you should fix your data.

We have a less strict triangulator actually, add the option `--sloppy` to the triangulate operator, and this should work (but the results of the triangulation might not be valid, but it shouldn't crash)
