### ISSUE TITLE
CityJSON to OBJ fails under Python 3.11.0

### ISSUE THREAD

**Issue by paulojraposo** [cityjson/cjio#161]
Thanks for this software!

Ubuntu Linux 22.04 here. It seems to work just fine under a Python 3.9.16 conda environment on my machine, but in one running 3.11.0 I get this:

```
$ python --version
Python 3.11.0
$ cjio /home/paulo/Downloads/CityJSON_Tutorial/twobuildings.city.json export obj /home/paulo/Downloads/CityJSON_Tutorial/twobuildings.obj 
Traceback (most recent call last):
  File "/home/paulo/anaconda3/envs/CityJSON/bin/cjio", line 5, in <module>
    from cjio.cjio import cli
  File "/home/paulo/anaconda3/envs/CityJSON/lib/python3.11/site-packages/cjio/cjio.py", line 55, in <module>
    @cli.resultcallback()
     ^^^^^^^^^^^^^^^^^^
AttributeError: 'Group' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?
$ cjio --version
Traceback (most recent call last):
  File "/home/paulo/anaconda3/envs/CityJSON/bin/cjio", line 5, in <module>
    from cjio.cjio import cli
  File "/home/paulo/anaconda3/envs/CityJSON/lib/python3.11/site-packages/cjio/cjio.py", line 55, in <module>
    @cli.resultcallback()
     ^^^^^^^^^^^^^^^^^^
AttributeError: 'Group' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?
```

**Comment by hugoledoux** [comment]
I think your cjio is old, this was fixed in d2f1732d3f1284b4f80cc6ca87f92d248a6b4e6e

If you install the latest version it should work
