### ISSUE TITLE
KeyError: appearance when removing textures

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/cjio#24]
From #23 

@cfrank0214 could you please attach the `test.json` file to a reply so we can take a look? You'll probably need to zip it first.

```
cjio test.json remove_textures export test.obj
Parsing test.json
Remove all textures
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.7/bin/cjio", line 8, in
sys.exit(cli())
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in call
return self.main(*args, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1164, in invoke
return _process_result(rv)
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1102, in _process_result
**ctx.params)
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cjio/cjio.py", line 96, in process_pipeline
cm = processor(cm)
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cjio/cjio.py", line 406, in processor
cm.remove_textures()
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cjio/cityjson.py", line 839, in remove_textures
if self.j["appearance"] is None or len(self.j["appearance"]) == 0:
KeyError: 'appearance'
```

**Comment by balazsdukai** [comment]
I could not reproduce this on v0.7.3
